/**
 * KAAF University Noticeboard – Academic Calendar Seed
 * Seeds the Second Semester 2025/2026 events into MongoDB.
 */

"use strict";

require("dotenv").config();
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");

// ── DB connection ─────────────────────────────────────────────────────────────
const MONGO_URI =
  process.env.MONGODB_URI ||
  process.env.MONGO_URI ||
  "mongodb://localhost:27017/kaaf_noticeboard";

// ── Academic Calendar Data ────────────────────────────────────────────────────
const ACADEMIC_EVENTS = [
  {
    title: "Opening of Registration System (No Fine)",
    description:
      "Opening of the Registration System for all students without a fine.",
    eventType: "Academic",
    eventDate: new Date("2026-01-05"),
    startTime: "00:00",
    endTime: "23:59",
    venue: "KAAF University – Student Portal (Online)",
    location: "Online Portal",
    targetAudience: "all",
    isActive: true,
    isFeatured: true,
    tags: ["registration", "semester"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["all"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Re-opening / Arrival of ALL Continuing Students",
    description: "All continuing students are expected to return to campus.",
    eventType: "Academic",
    eventDate: new Date("2026-01-09"),
    startTime: "08:00",
    endTime: "18:00",
    venue: "KAAF University Campus",
    location: "Main Campus",
    targetAudience: "all",
    isActive: true,
    isFeatured: false,
    tags: ["resumption", "semester"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["all"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Lectures Begin – Regular Students",
    description: "Lectures commence for all regular (weekday) students.",
    eventType: "Academic",
    eventDate: new Date("2026-01-12"),
    startTime: "08:00",
    endTime: "17:00",
    venue: "KAAF University Campus",
    location: "Various Lecture Halls",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["lectures", "semester"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Lectures Begin – Weekend Students",
    description: "Lectures commence for all weekend programme students.",
    eventType: "Academic",
    eventDate: new Date("2026-01-16"),
    startTime: "08:00",
    endTime: "17:00",
    venue: "KAAF University Campus",
    location: "Weekend Lecture Halls",
    targetAudience: "student",
    isActive: true,
    isFeatured: false,
    tags: ["lectures", "weekend", "semester"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Late Registration with a Fine",
    description:
      "Students who have not yet registered may do so with a penalty fee.",
    eventType: "Academic",
    eventDate: new Date("2026-01-26"),
    startTime: "09:00",
    endTime: "16:00",
    venue: "KAAF University – Registrar's Office",
    location: "Registrar's Office",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["registration", "fine", "late"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Registration Ends for ALL Students",
    description: "Final deadline for student registration.",
    eventType: "Academic",
    eventDate: new Date("2026-02-02"),
    startTime: "09:00",
    endTime: "17:00",
    venue: "KAAF University – Registrar's Office",
    location: "Registrar's Office",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["registration", "deadline"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Orientation Week",
    description: "Orientation programme for all new and continuing students.",
    eventType: "Social",
    eventDate: new Date("2026-02-09"),
    startTime: "09:00",
    endTime: "17:00",
    venue: "KAAF University Campus – Main Auditorium",
    location: "Main Auditorium",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["orientation", "fresh-students"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Matriculation Ceremony",
    description:
      "Formal matriculation ceremony for all newly admitted students.",
    eventType: "Social",
    eventDate: new Date("2026-02-20"),
    startTime: "10:00",
    endTime: "14:00",
    venue: "KAAF University Campus – Great Hall",
    location: "Great Hall",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["matriculation", "ceremony"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Mid-Semester Assessment – Weekend Students",
    description: "Mid-semester assessments for weekend programme students.",
    eventType: "Academic",
    eventDate: new Date("2026-02-27"),
    startTime: "08:00",
    endTime: "18:00",
    venue: "KAAF University Campus",
    location: "Various Venues",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["assessment", "mid-semester", "weekend", "exams"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Moderation of Questions",
    description: "Moderation of examination questions by academic boards.",
    eventType: "Workshop",
    eventDate: new Date("2026-03-09"),
    startTime: "10:00",
    endTime: "16:00",
    venue: "KAAF University Campus – Faculty Offices",
    location: "Faculty Offices",
    targetAudience: "faculty",
    isActive: true,
    isFeatured: false,
    tags: ["moderation", "exams", "faculty"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["faculty"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Mid-Semester Assessment – Regular Students",
    description: "Mid-semester assessments for regular programme students.",
    eventType: "Academic",
    eventDate: new Date("2026-03-23"),
    startTime: "08:00",
    endTime: "18:00",
    venue: "KAAF University Campus",
    location: "Various Venues",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["assessment", "mid-semester", "regular", "exams"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "SRC & PUSAG Week",
    description: "Annual SRC and PUSAG Week celebrations.",
    eventType: "Cultural",
    eventDate: new Date("2026-03-15"),
    startTime: "09:00",
    endTime: "22:00",
    venue: "KAAF University Campus",
    location: "Campus Grounds",
    targetAudience: "all",
    isActive: true,
    isFeatured: true,
    tags: ["SRC", "PUSAG", "student-week", "cultural"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["all"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Lectures End – ALL Students",
    description: "Last day of lectures for all students.",
    eventType: "Academic",
    eventDate: new Date("2026-03-29"),
    startTime: "08:00",
    endTime: "17:00",
    venue: "KAAF University Campus",
    location: "Various Lecture Halls",
    targetAudience: "all",
    isActive: true,
    isFeatured: false,
    tags: ["lectures", "end", "semester"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["all"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Revision Week – ALL Students",
    description: "Dedicated revision week for all students.",
    eventType: "Academic",
    eventDate: new Date("2026-03-30"),
    startTime: "08:00",
    endTime: "17:00",
    venue: "KAAF University Campus",
    location: "Various Venues",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["revision", "exams", "preparation"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "End-of-Semester Examinations – ALL Students",
    description: "Final examinations for all students.",
    eventType: "Academic",
    eventDate: new Date("2026-04-06"),
    startTime: "08:00",
    endTime: "18:00",
    venue: "KAAF University Campus – Examination Halls",
    location: "Examination Halls",
    targetAudience: "student",
    isActive: true,
    isFeatured: true,
    tags: ["exams", "end-of-semester", "final"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["student"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Semester Break – ALL Programmes",
    description: "Official semester break for all programmes.",
    eventType: "Academic",
    eventDate: new Date("2026-04-27"),
    startTime: "00:00",
    endTime: "23:59",
    venue: "KAAF University",
    location: "University",
    targetAudience: "all",
    isActive: true,
    isFeatured: false,
    tags: ["break", "semester", "holiday"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["all"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Departmental Board Meeting",
    description: "Departmental Board Meeting for all academic departments.",
    eventType: "Workshop",
    eventDate: new Date("2026-05-27"),
    startTime: "10:00",
    endTime: "15:00",
    venue: "KAAF University Campus – Board Room",
    location: "Board Room",
    targetAudience: "faculty",
    isActive: true,
    isFeatured: false,
    tags: ["board-meeting", "departmental", "faculty"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["faculty"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Faculty Board Meeting",
    description: "Faculty Board Meeting for all faculties.",
    eventType: "Workshop",
    eventDate: new Date("2026-05-29"),
    startTime: "10:00",
    endTime: "15:00",
    venue: "KAAF University Campus – Faculty Board Room",
    location: "Faculty Board Room",
    targetAudience: "faculty",
    isActive: true,
    isFeatured: false,
    tags: ["board-meeting", "faculty"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["faculty"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
  {
    title: "Academic Board Meeting",
    description: "Full Academic Board Meeting of KAAF University College.",
    eventType: "Seminar",
    eventDate: new Date("2026-06-10"),
    startTime: "10:00",
    endTime: "16:00",
    venue: "KAAF University Campus – Senate Chamber",
    location: "Senate Chamber",
    targetAudience: "faculty",
    isActive: true,
    isFeatured: false,
    tags: ["academic-board", "senate", "faculty"],
    status: "upcoming",
    isPublished: true,
    targetDepartments: ["all"],
    targetRoles: ["faculty"],
    participationMode: "offline",
    registeredCount: 0,
    checkedInCount: 0,
    waitlistCount: 0,
    views: 0,
    uniqueViews: 0,
    shares: 0,
    likes: 0,
    feedbackEnabled: true,
    isRegistrationRequired: false,
    registrationFee: 0,
  },
];

// ── Seed function ─────────────────────────────────────────────────────────────
async function seed() {
  console.log("🌱 Connecting to MongoDB...");
  await mongoose.connect(MONGO_URI);
  console.log("✅ Connected:", mongoose.connection.host);

  const Event = require("../models/Event");
  const User = require("../models/User");

  // Find or create admin user
  let organizer = await User.findOne({ email: "boakyesamuel189@gmail.com" });

  if (!organizer) {
    console.log("👤 Creating admin user...");
    const hashedPassword = await bcrypt.hash("sam059SAM@#$", 10);
    organizer = await User.create({
      firstName: "YAW",
      lastName: "BOAKYE",
      email: "boakyesamuel189@gmail.com",
      password: hashedPassword,
      role: "admin",
      isActive: true,
    });
    console.log(
      `✅ Created admin user: ${organizer.firstName} ${organizer.lastName}`,
    );
  } else {
    console.log(
      `✅ Using existing admin: ${organizer.firstName} ${organizer.lastName}`,
    );
  }

  let created = 0;
  let skipped = 0;

  for (const eventData of ACADEMIC_EVENTS) {
    const existing = await Event.findOne({ title: eventData.title });
    if (existing) {
      console.log(`  ⏭  Skipping: ${eventData.title}`);
      skipped++;
      continue;
    }

    const payload = {
      ...eventData,
      organizer: organizer._id,
      organizerName: `${organizer.firstName} ${organizer.lastName}`,
      organizerEmail: organizer.email,
      createdBy: organizer._id,
      updatedBy: organizer._id,
    };

    try {
      await Event.create(payload);
      console.log(`  ✅ Created: ${eventData.title}`);
      created++;
    } catch (err) {
      console.error(`  ❌ Failed: ${eventData.title} -`, err.message);
    }
  }

  console.log(`\n🎉 Seed complete — ${created} created, ${skipped} skipped`);
  console.log(`📊 Total events: ${await Event.countDocuments()}`);

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
